#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Stream-Buffered
Version  : 0.03
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/D/DO/DOY/Stream-Buffered-0.03.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DO/DOY/Stream-Buffered-0.03.tar.gz
Summary  : temporary buffer to save bytes
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan

%description
NAME
Stream::Buffered - temporary buffer to save bytes
SYNOPSIS
my $buf = Stream::Buffered->new($length);
$buf->print($bytes);

%package dev
Summary: dev components for the perl-Stream-Buffered package.
Group: Development
Provides: perl-Stream-Buffered-devel = %{version}-%{release}
Requires: perl-Stream-Buffered = %{version}-%{release}
Requires: perl-Stream-Buffered = %{version}-%{release}

%description dev
dev components for the perl-Stream-Buffered package.


%prep
%setup -q -n Stream-Buffered-0.03

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Stream/Buffered.pm
/usr/lib/perl5/vendor_perl/5.28.2/Stream/Buffered/Auto.pm
/usr/lib/perl5/vendor_perl/5.28.2/Stream/Buffered/File.pm
/usr/lib/perl5/vendor_perl/5.28.2/Stream/Buffered/PerlIO.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Stream::Buffered.3
